Release 2 0 0
plentymarkets/plugin-elastic-export-shopzilla-de pull request #3
Opened 2017-07-21 15:25 UTC by jschaakplenty

@plentymarkets/team-multichannel-koboldmaki 
@hschwab

2017-07-24 12:07 UTC, hschwab approved these changes

2017-07-24 13:44 UTC, mariusbippig requested changes

2017-07-24 13:44 UTC, Desentyer commented on src/Generator/ShopzillaDE.php
> +    const CHARACTER_TYPE_AGE_GROUP	= 'age_group';
Wir haben global für Merkmale den Begriff Properties eingeführt, weshalb es geil wäre, wenn du das hier für die Konstanten berücksichtigen würdest :D

2017-07-24 13:44 UTC, Desentyer commented on src/Generator/ShopzillaDE.php
> +    private function getCondition(int $conditionId):string
Self describing functions, woop woop!

2017-07-24 13:44 UTC, Desentyer commented on src/Helper/AttributeHelper.php
> +    const CHARACTER_TYPE_SIZE						= 'size';
Dasselbe wie oben: Property statt Character

2017-07-25 07:10 UTC, mariusbippig approved these changes

2017-07-26 09:36 UTC, merged